// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const appsync =  {
    "aws_appsync_graphqlEndpoint": "https://jalxzy6w4rh77fh3xidwzo7cuu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_appsync_apiKey": "null",
};

export default appsync;